language: ruby
rvm: 2.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache: bundler

script:
  - bin/rake app:db:setup app:db:test:load
  - bin/rspec
